name: CI DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_test_sast_deps:
    name: Build, Test, SAST & Dep Scan
    runs-on: ubuntu-latest
    # 👇 Todos los "run:" de este job se ejecutan dentro de /app
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Start app & run unit test
        run: |
          node src/app.js &
          APP_PID=$!
          for i in {1..30}; do
            curl -sf http://localhost:3000/healthz && break
            sleep 1
          done
          npm test
          kill $APP_PID

      - name: Semgrep SAST (OWASP + custom)
        uses: returntocorp/semgrep-action@v1
        with:
          # OJO: como el job corre "run" dentro de /app, tu .semgrep.yml está en el nivel superior (../)
          config: >
            p/owasp-top-ten
            ../.semgrep.yml
        env:
          # (Opcional) para dashboards en Semgrep App:
          # SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_ENABLE_VERSION_CHECK: "0"

      - name: Trivy FS (dependency scan en /app)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: app
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          format: table
          exit-code: '0'   # ← modo didáctico (no rompe). Cambia a '1' para quality gate.

  docker_image_and_scan:
    name: Build Docker image & Trivy Image
    needs: build_test_sast_deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-demo-app:ci ./app

      - name: Trivy Image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: devsecops-demo-app:ci
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          format: table
          exit-code: '0'   # ← cámbialo a '1' cuando quieras que falle si hay vulns

  dast_zap:
    name: ZAP Baseline (DAST)
    needs: build_test_sast_deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image (app)
        run: docker build -t devsecops-demo-app:ci ./app

      - name: Create docker network
        run: docker network create zapnet

      - name: Start app container on zapnet
        run: |
          docker run -d --rm --name demoapp --network zapnet -p 3000:3000 devsecops-demo-app:ci
          for i in {1..60}; do
            docker run --rm --network zapnet curlimages/curl:8.10.1 -sf demoapp:3000/healthz && break
            sleep 1
          done

      - name: OWASP ZAP Baseline (same docker network)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://demoapp:3000'
          rules_file_name: '.zap/rules.tsv'
          allow_issue_writing: false
          cmd_options: '-a'
          docker_run_args: '--network zapnet'

      - name: Stop app & cleanup
        if: always()
        run: |
          docker rm -f demoapp || true
          docker network rm zapnet || true

