name: CI DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_test_sast_deps:
    name: Build, Test, SAST & Dep Scan
    runs-on: ubuntu-latest
    # 👇 Todos los "run:" de este job se ejecutan dentro de /app
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Start app & run unit test
        run: |
          node src/app.js &
          APP_PID=$!
          for i in {1..30}; do
            curl -sf http://localhost:3000/healthz && break
            sleep 1
          done
          npm test
          kill $APP_PID

      - name: Semgrep SAST (OWASP + custom)
        uses: returntocorp/semgrep-action@v1
        with:
          # OJO: como el job corre "run" dentro de /app, tu .semgrep.yml está en el nivel superior (../)
          config: >
            p/owasp-top-ten
            ../.semgrep.yml
        env:
          # (Opcional) para dashboards en Semgrep App:
          # SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_ENABLE_VERSION_CHECK: "0"

      - name: Trivy FS (dependency scan en /app)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: app
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          format: table
          exit-code: '0'   # ← modo didáctico (no rompe). Cambia a '1' para quality gate.

  docker_image_and_scan:
    name: Build Docker image & Trivy Image
    needs: build_test_sast_deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-demo-app:ci ./app

      - name: Trivy Image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: devsecops-demo-app:ci
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          format: table
          exit-code: '0'   # ← cámbialo a '1' cuando quieras que falle si hay vulns

  dast_zap:
    name: ZAP Baseline (DAST)
    needs: build_test_sast_deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image (app)
        run: docker build -t devsecops-demo-app:ci ./app

      - name: Create docker network
        run: docker network create zapnet

      - name: Run OWASP ZAP baseline scan
        run: |
          mkdir -p reports
          docker run --rm \
            -v "$(pwd)/reports:/zap/wrk/reports" \
            --network zapnet \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://devsecops-demo-app:3000 \
            -r reports/zap-report.html -x reports/zap-report.xml -w reports/zap-warn.md


      - name: Start app container on zapnet
        run: |
          docker run -d --rm --name demoapp --network zapnet -p 3000:3000 devsecops-demo-app:ci
          # Espera a que /healthz responda desde la MISMA red docker
          for i in {1..90}; do
            docker run --rm --network zapnet curlimages/curl:8.10.1 -sf demoapp:3000/healthz && break
            sleep 1
          done

      - name: Run ZAP Baseline (manual docker run)
        run: |
          mkdir -p reports
          docker run --rm --network zapnet \
            -v "$GITHUB_WORKSPACE:/zap/wrk:rw" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t "http://demoapp:3000" \
              -a \
              -I \
              -x "/zap/wrk/reports/zap-report.xml" \
              -w "/zap/wrk/reports/zap-warn.md" \
              -r "/zap/wrk/reports/zap-report.html" || true

      - name: List reports (debug)
        run: ls -la reports || true

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: reports/**

      - name: Stop app & cleanup
        if: always()
        run: |
          docker rm -f demoapp || true
          docker network rm zapnet || true


